1_CoreMvcPersonel/CoreMvcPersonel/Models/Admin.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreMvcDepartman.Models
{
    public class Admin
    {
        [Key]
        public int AdminID { get; set; }
        [Column(TypeName ="Varchar(20)")]
        public string Kullanici { get; set; }
        [Column(TypeName ="Varchar(10)")]
        public string Sifre { get; set; }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace CoreMvcDepartman.Models
{
    public class Context:DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=DESKTOP-GAARB72\\SQLEXPRESS; database=CoreMvcDepartman; integrated security=true; TrustServerCertificate=true");
        }
        public DbSet<Personel> Personeller { get; set; }
        public DbSet<Departman> Departmanlar { get; set; }
        public DbSet<Admin> Adminler { get; set; }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Models/Departman.cs
using System.ComponentModel.DataAnnotations;

namespace CoreMvcDepartman.Models
{
    public class Departman
    {
        [Key]
        public int DepartmanId { get; set; }
        public string DepartmanAd { get; set; }
        public IList<Personel> Personeller { get; set; }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Models/ErrorViewModel.cs
namespace CoreMvcDepartman.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Models/Personel.cs
using System.ComponentModel.DataAnnotations;

namespace CoreMvcDepartman.Models
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }
        public int DepartmanId { get; set; }
        public Departman Departman { get; set; }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Controllers/DepartmanController.cs
using CoreMvcDepartman.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreMvcDepartman.Controllers
{
    public class DepartmanController : Controller
    {
        Context context = new Context();

        [Authorize]
        public IActionResult Index()
        {
            var degerler = context.Departmanlar.ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniDepartman()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniDepartman(Departman d)
        {
            context.Departmanlar.Add(d);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartmanSil(int id)
        {
            var silinecekDepartman = context.Departmanlar.Find(id);
            context.Departmanlar.Remove(silinecekDepartman);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartmanGetir(int id)
        {
            var departman = context.Departmanlar.Find(id);
            return View("DepartmanGetir", departman);
        }
        public IActionResult DepartmanGuncelle(Departman d)
        {
            var departman = context.Departmanlar.Find(d.DepartmanId);
            departman.DepartmanAd = d.DepartmanAd;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartmanDetay(int id)
        {
            var personeller = context.Personeller.Where(x => x.DepartmanId == id).ToList();
            var departmanAd = context.Departmanlar.Where(x => x.DepartmanId == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.departmanAd = departmanAd;
            return View(personeller);
        }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CoreMvcDepartman.Models;

namespace CoreMvcDepartman.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Controllers/LogInController.cs
using CoreMvcDepartman.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CoreMvcDepartman.Controllers
{
    public class LogInController : Controller
    {
        Context context = new Context();
        [HttpGet]
        public IActionResult GirisYap()
        {
            return View();
        }
        public async Task<IActionResult> GirisYap(Admin p)
        {
            var bilgiler = context.Adminler.FirstOrDefault(x => x.Kullanici == p.Kullanici && x.Sifre == p.Sifre);
            if(bilgiler != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, p.Kullanici)
                };
                var userIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Personel");
            }
            return View();
        }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Controllers/PersonelController.cs
using CoreMvcDepartman.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CoreMvcDepartman.Controllers
{
    public class PersonelController : Controller
    {
        Context context = new Context();
        
        [Authorize]
        public IActionResult Index()
        {
            var degerler = context.Personeller.Include(x=>x.Departman).ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniPersonel()
        {
            List<SelectListItem> degerler = (from x in context.Departmanlar.ToList()
                                             select new SelectListItem()
                                             {
                                                 Text = x.DepartmanAd,
                                                 Value = x.DepartmanId.ToString()
                                             }).ToList();
            ViewBag.departmanlar = degerler;
            return View();
        }
        public IActionResult YeniPersonel(Personel p)
        {
            var departman = context.Departmanlar.Where(x => x.DepartmanId == p.Departman.DepartmanId).FirstOrDefault();
            p.Departman = departman;
            context.Personeller.Add(p);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult PersonelGuncelle(int id)
        {
            var deger = context.Personeller.Find(id);
            List<SelectListItem> degerler = (from x in context.Departmanlar.ToList()
                                             select new SelectListItem()
                                             {
                                                 Value = x.DepartmanId.ToString(),
                                                 Text = x.DepartmanAd
                                             }).ToList();
            ViewBag.departmanlar = degerler;
            return View(deger);
        }
        [HttpPost]
        public IActionResult PersonelGuncelle(Personel p)
        {
            var personel = context.Personeller.Find(p.PersonelId);
            personel.Ad = p.Ad;
            personel.Soyad = p.Soyad;
            personel.Sehir = p.Sehir;
            personel.DepartmanId = p.DepartmanId;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult PersonelSil(int id)
        {
            var degerler = context.Personeller.Find(id);
            context.Personeller.Remove(degerler);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

1_CoreMvcPersonel/CoreMvcPersonel/Views/Departman/DepartmanDetay.cshtml
@using CoreMvcDepartman.Models
@model List<Personel>
@{
    ViewData["Title"] = "DepartmanDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<h2>@ViewBag.departmanAd Departamanı</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
    </tr>
    @foreach (var deger in Model)
    {
        <tr>
            <td>@deger.PersonelId</td>
            <td>@deger.Ad</td>
            <td>@deger.Soyad</td>
            <td>@deger.Sehir</td>
        </tr>
    }
</table>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Departman/DepartmanGetir.cshtml
@model CoreMvcDepartman.Models.Departman
@{
    ViewData["Title"] = "DepartmanGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    @Html.Label("Departman ID:")
    @Html.TextBoxFor(x => x.DepartmanId, new { @class = "form-control" })
    <br />
    @Html.Label("Departman Adı:")
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Departman Güncelle</button>
}

1_CoreMvcPersonel/CoreMvcPersonel/Views/Departman/Index.cshtml
@using CoreMvcDepartman.Models
@model List<Departman>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var deger in Model)
    {
        <tr>
            <td>@deger.DepartmanId</td>
            <td>@deger.DepartmanAd</td>
            <td><a href="/Departman/DepartmanSil/@deger.DepartmanId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@deger.DepartmanId" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@deger.DepartmanId" class="btn btn-warning">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Departman/YeniDepartman/" class="btn btn-primary">Yeni Departman</a>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Departman/YeniDepartman.cshtml
@model CoreMvcDepartman.Models.Departman
@{
    ViewData["Title"] = "YeniDepartman";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<form method="post">
    @Html.Label("Departman Adı:")
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Departman Ekle</button>
</form>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Personel/Index.cshtml
@model List<CoreMvcDepartman.Models.Personel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var deger in Model)
    {
        <tr>
            <td>@deger.PersonelId</td>
            <td>@deger.Ad</td>
            <td>@deger.Soyad</td>
            <td>@deger.Sehir</td>
            <td>@deger.Departman.DepartmanAd</td>
            <td><a href="/Personel/PersonelSil/@deger.PersonelId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personel/PersonelGuncelle/@deger.PersonelId" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Personel/YeniPersonel/" class="btn btn-primary">Yeni Personel</a>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Personel/PersonelGuncelle.cshtml
@model CoreMvcDepartman.Models.Personel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<form method="post">
    @Html.Label("Personel ID:")
    @Html.TextBoxFor(x => x.PersonelId, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Adı:")
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Soyadı:")
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Şehri:")
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Departmanı:")
    @Html.DropDownListFor(x=> x.DepartmanId, (List<SelectListItem>)ViewBag.departmanlar, new {@class = "form-control"})
    <br />
    <button class="btn btn-primary">Personeli Güncelle</button>
</form>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Personel/YeniPersonel.cshtml
@model CoreMvcDepartman.Models.Personel
@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<form method="post">
    @Html.Label("Personel Adı:")
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Soyadı:")
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Şehri:")
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.Label("Personel Departmanı:")
    @Html.DropDownListFor(x=> x.Departman.DepartmanId, (List<SelectListItem>)ViewBag.departmanlar,new{@class="form-control"})
    <br />
    <button class="btn btn-primary">Personel Ekle</button>
</form>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreMvcDepartman</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreMvcDepartman.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreMvcDepartman</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CoreMvcDepartman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

1_CoreMvcPersonel/CoreMvcPersonel/Views/Shared/_TestLayout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html>
<head>
	<title>W3.CSS</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>

	<!-- Sidebar -->
	<div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
		<h3 class="w3-bar-item">Menüler</h3>
		<a href="/Departman/Index" class="w3-bar-item w3-button">Departmanlar</a>
		<a href="/Personel/Index" class="w3-bar-item w3-button">Personeller</a>
		@* <a href="#" class="w3-bar-item w3-button">Hakkımızda</a> *@
		@* <a href="#" class="w3-bar-item w3-button">Çıkış</a> *@
	</div>

	<!-- Page Content -->
	<div style="margin-left:15%">

		<div class="w3-container w3-teal">
			<h1>ASP.NET Core MVC Proje Geliştirme</h1>
		</div>

		<div class="w3-container">
			@RenderBody()
		</div>

	</div>

</body>
</html>